# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.building.build_main import Analysis, PYZ, EXE, COLLECT
from PyInstaller.config import CONF
import sys
import os

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('web_app.py', '.'),
        ('src', 'src'),
    ],
    hiddenimports=[
        'streamlit',
        'streamlit.web.cli',
        'streamlit.runtime.scriptrunner',
        'streamlit.runtime.scriptrunner.script_runner',
        'streamlit.runtime.scriptrunner.magic',
        'streamlit.runtime.caching',
        'streamlit.runtime.state',
        'streamlit.runtime.uploaded_file_manager',
        'streamlit.runtime.metrics_util',
        'streamlit.runtime.forward_msg_cache',
        'streamlit.runtime.forward_msg_queue',
        'streamlit.runtime.runtime',
        'streamlit.runtime.app_session',
        'streamlit.runtime.session_data',
        'streamlit.runtime.media_file_manager',
        'streamlit.runtime.memory_session_storage',
        'streamlit.runtime.stats',
        'streamlit.proto',
        'streamlit.proto.BackMsg_pb2',
        'streamlit.proto.Block_pb2',
        'streamlit.proto.BokehChart_pb2',
        'streamlit.proto.Button_pb2',
        'streamlit.proto.ChatInput_pb2',
        'streamlit.proto.Checkbox_pb2',
        'streamlit.proto.ColorPicker_pb2',
        'streamlit.proto.Common_pb2',
        'streamlit.proto.Components_pb2',
        'streamlit.proto.DataFrame_pb2',
        'streamlit.proto.DateInput_pb2',
        'streamlit.proto.Delta_pb2',
        'streamlit.proto.DocString_pb2',
        'streamlit.proto.DownloadButton_pb2',
        'streamlit.proto.Element_pb2',
        'streamlit.proto.Empty_pb2',
        'streamlit.proto.Exception_pb2',
        'streamlit.proto.Favicon_pb2',
        'streamlit.proto.FileUploader_pb2',
        'streamlit.proto.ForwardMsg_pb2',
        'streamlit.proto.GitInfo_pb2',
        'streamlit.proto.GraphVizChart_pb2',
        'streamlit.proto.Heading_pb2',
        'streamlit.proto.Html_pb2',
        'streamlit.proto.IFrame_pb2',
        'streamlit.proto.Image_pb2',
        'streamlit.proto.Json_pb2',
        'streamlit.proto.LabelVisibilityMessage_pb2',
        'streamlit.proto.LinkButton_pb2',
        'streamlit.proto.Markdown_pb2',
        'streamlit.proto.Metric_pb2',
        'streamlit.proto.MultiSelect_pb2',
        'streamlit.proto.NamedDataSet_pb2',
        'streamlit.proto.NewSession_pb2',
        'streamlit.proto.NumberInput_pb2',
        'streamlit.proto.PageConfig_pb2',
        'streamlit.proto.PageInfo_pb2',
        'streamlit.proto.PageLink_pb2',
        'streamlit.proto.PageNotFound_pb2',
        'streamlit.proto.PageProfile_pb2',
        'streamlit.proto.PagesChanged_pb2',
        'streamlit.proto.PlotlyChart_pb2',
        'streamlit.proto.Progress_pb2',
        'streamlit.proto.Radio_pb2',
        'streamlit.proto.Selectbox_pb2',
        'streamlit.proto.SessionEvent_pb2',
        'streamlit.proto.Skeleton_pb2',
        'streamlit.proto.Slider_pb2',
        'streamlit.proto.Snow_pb2',
        'streamlit.proto.Spinner_pb2',
        'streamlit.proto.TextArea_pb2',
        'streamlit.proto.TextInput_pb2',
        'streamlit.proto.TimeInput_pb2',
        'streamlit.proto.Toast_pb2',
        'streamlit.proto.VegaLiteChart_pb2',
        'streamlit.proto.Video_pb2',
        'streamlit.proto.WidgetStates_pb2',
        'altair',
        'altair.vegalite.v5',
        'pyarrow',
        'pyarrow.compute',
        'pandas',
        'numpy',
        'packaging',
        'protobuf',
        'google.protobuf',
        'tornado',
        'watchdog',
        'blinker',
        'cachetools',
        'click',
        'requests',
        'toml',
        'typing_extensions',
        'validators',
        'git',
        'pydeck',
        'rich',
        'tenacity',
        'jsonschema',
        'urllib3',
        'charset_normalizer',
        'certifi',
        'idna',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='VisionEnvChecker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # 保留控制台看错误
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
